on:
  issue_comment:
    types: [created, edited]

jobs:
  add-comment-to-asana:
    runs-on: ubuntu-latest
    name: Add Comment to Asana Task
    steps:
      - name: Add comment to Asana task
        env:
          ASANA_SECRET: ${{ secrets.ASANA_SECRET }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          PR_URL: ${{ github.event.issue.html_url }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_TITLE: ${{ github.event.issue.title }}
          PR_STATE: ${{ github.event.issue.state }}
        run: |
          curl -X POST https://app.asana.com/api/1.0/tasks/<TASK_ID>/stories \
          -H "Authorization: Bearer $ASANA_SECRET" \
          -H "Content-Type: application/json" \
          -d '{
                "text": "New comment on PR #'"$PR_NUMBER"' (state: '"$PR_STATE"'): '"$PR_URL"' \n\n'"$COMMENT_BODY"'"
              }'
