on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/comment-on-task-github-action@latest
        id: createComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
          comment-text: >
            Pull Request {{ github.event.pull_request.title }} is {{ github.event.action }}.
            PR URL: {{ github.event.pull_request.html_url }}
            User: {{ github.event.pull_request.user.login }}
      - name: Get status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
